(defun my-go-lang-config ()
  (add-hook 'before-save-hook #'gofmt-before-save nil 'local)
  (local-set-key (kbd "M-.") 'godef-jump)
  (local-set-key (kbd "M-,") 'godef-jump-back)
  (add-to-list 'load-path "/usr/local/go/src/github.com/dougm/goflymake")
  (global-flycheck-mode 1)
  ;;(add-to-list 'load-path (expand-file-name "~/.emacs.d/src"))
  ;(require 'auto-complete-config)
  ;;(ac-config-default)
  )
(require 'go-autocomplete)
(add-hook 'go-mode-hook #'my-go-lang-config)
(provide 'my-go-conf)
